name: Release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*' # e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x          

    - name: Build project
      run: dotnet build -c Release

    - name: Pack NuGet package
      run: dotnet pack -c Release -o ./nupkgs

    - name: Push prelease package to nuget.org
      if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/preview'
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" -p VersionSuffix='$(preview-[System.DateTime]::UtcNow.ToString("yyyyMMdd"))' -k ${{ secrets.NUGET_API_KEY }}

    - name: Push to nuget.org
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" -p Version='${GITHUB_REF_NAME#v}' -k ${{ secrets.NUGET_API_KEY }}
