name: Release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*' # e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x          

    - name: Build project
      run: dotnet build -c Release

    - name: Set Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION_PREFIX=${GITHUB_REF_NAME#v}
        echo "VERSION_PREFIX=$VERSION_PREFIX"
        dotnet pack ./src/GaussDB/GaussDB.csproj -c Release -o ./artifacts/nupkgs -p VersionPrefix=$VERSION_PREFIX

    - name: Set Preview Package
      if: github.event_name == 'workflow_dispatch'
      run: |
        VERSION_SUFFIX=$(date -u +"%Y%m%d%H%M")
        echo $VERSION_SUFFIX
        dotnet pack ./src/GaussDB/GaussDB.csproj -c Release -o ./artifacts/nupkgs -p VersionSuffix=$VERSION_SUFFIX

    - name: Push to nuget.org
      run: |
        dotnet nuget push "./artifacts/nupkgs/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
